### ISSUE TITLE
Performing clipboard capture with a blank clipboard uploads a full-screen screenshot

### ISSUE THREAD

**Issue by Tursko** [shotr-io/shotr-3#16] opened 2021-01-08 04:31 UTC
will edit later

**Comment by ThrDev** [comment] 2021-01-13 14:28
I've checked into this and am not able to reproduce. Re-open if you can reproduce this.

**Closed by ThrDev** 2021-01-13 14:28 UTC
Labels: bug

**Comment by Tursko** [comment] 2021-01-13 14:32
You know what. It's an after effect of using print screen as your hotkey now that I think about it.
