### ISSUE TITLE
Error when setting prtscn as hotkey on Windows 11

### ISSUE THREAD

**Issue by dreyes333** [shotr-io/shotr-3#136] opened 2022-01-22 22:59 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
Windows 11 key binding issues on fresh install of shotr

### Steps to reproduce the bug
1.) Once shotr opens try to set hotkey to prtscn

**Actual result:** Error message when set, looks like it is set but when hitting prtscn nothing happened NOTE: I was able to change the hotkey to something else (lets say prtscn + shift) and it worked. After that I changed it to prtscn again no error message and it worked just fine.

**Expected result:** Hotkey should have been set 

### Version info

**Shotr Version:** 3.1.5
Windows 11

**Comment by zacbre** [comment] 2022-01-25 02:03
Hey @dreyes333!

I was able to set the prntscn key with my windows 11 install and even on start. Are you running anything else that might be taking over that key?

**Comment by dreyes333** [comment] 2022-01-25 02:10
> Hey @dreyes333!
> 
> I was able to set the prntscn key with my windows 11 install and even on start. Are you running anything else that might be taking over that key?

No, I am not. I think it is Important to note that error happened upon fresh install of shotr and Windows 11. Was going to uninstall and reinstall to see if it would happen again but ahvent had a chance to look.

**Comment by Tursko** [comment] 2022-01-26 00:53
Probably because snipping tool can reserve that key now.
![image](https://user-images.githubusercontent.com/18274896/151084675-2524bcef-f192-493f-9d88-d6ad618d2d3b.png)

**Comment by Tursko** [comment] 2022-05-24 20:00
We were never able to reproduce it. Let's close it for now.

**Closed** 2022-05-24 19:59 UTC
Labels: bug
